// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://suydomgvamwjwcrlznom.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN1eWRvbWd2YW13andjcmx6bm9tIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0Nzg0MzMsImV4cCI6MjA3MDA1NDQzM30.wvTiA6QonM4jTr8Mnm7EoHp6B2vK67ln5ZhyvXU5uI8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});